In [22]:
!pip install bsedata
from bsedata.bse import BSE
b = BSE()
print(b)
# Output:
# Driver Class for Bombay Stock Exchange (BSE)

# to execute "updateScripCodes" on instantiation
# b = BSE(update_codes = True)

Requirement already satisfied: bsedata in /usr/local/lib/python3.10/dist-packages (0.6.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bsedata) (4.12.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from bsedata) (2.31.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from bsedata) (4.9.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bsedata) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->bsedata) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->bsedata) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->bsedata) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->bsedata) (2024.2.2)
Driver Class for Bombay Stock Exchange (BSE)

In [23]:
# !pip install pandas
import pandas as pd

Stock_list = pd.read_csv('/content/sample_data/Stock_List.csv')
Equity = pd.read_csv('/content/sample_data/Equity.csv')

In [24]:
Equity['Security Code']

0       500002
1       500003
2       500008
3       500009
4       500012
         ...
4310    750835
4311    750836
4312    780014
4313    780016
4314    780018
Name: Security Code, Length: 4315, dtype: int64

In [25]:
Stock_list.head()

                   Name  Asset  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5
0            HDFC Bank   5.34%         NaN         NaN         NaN         NaN
1  Maruti Suzuki India   4.78%         NaN         NaN         NaN         NaN
2           ICICI Bank   4.50%         NaN         NaN         NaN         NaN
3   Larsen & Toubro Ltd  4.27%         NaN         NaN         NaN         NaN
4         Axis Bank Ltd  4.01%         NaN         NaN         NaN         NaN

In [26]:
!pip install fuzzywuzzy
from fuzzywuzzy import process

# Assuming equity and list are your DataFrames
# Replace 'name' with the actual column names you want to search in both DataFrames

def find_similar_values(equity, stock_list, equity_name_column, stock_list_column):
    # Create a dictionary to store the matched values
    matched_values = {}

    # Iterate through each value in the stock_list DataFrame
    for stock in stock_list[stock_list_column]:
        if not isinstance(stock, str):
            break
        # Use process.extractOne to find the most similar value in the equity DataFrame
        match, score, index = process.extractOne(stock, equity[equity_name_column])
        # If the similarity score is above a certain threshold, consider it a match
        if score >= 70:  # You can adjust the threshold as needed
            matched_values[stock] = {'equity_name': match, 'equity_code': equity.loc[index, 'Security Code']}

    # Create a new DataFrame with the matched values
    result_df = pd.DataFrame(list(matched_values.items()), columns=[stock_list_column, 'matched_values'])
    result_df[['equity_name', 'equity_code']] = pd.DataFrame(result_df['matched_values'].tolist())
    result_df = result_df.drop(columns=['matched_values'])
    result_df['Asset'] = Stock_list['Asset']
    print(result_df)
    return result_df

# # Call the function with your DataFrames and the column names
# result_dataframe = find_similar_values(equity, stock_list, 'name', 'stock')
# print(result_dataframe)

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.10/dist-packages (0.18.0)

In [27]:
# Assuming you already have equity and stock_list DataFrames

# Call the function with your DataFrames and column names
result_dataframe = find_similar_values(Equity, Stock_list, 'Security Name', 'Name')

# Display the result DataFrame
print(result_dataframe)

                                     Name  \
0                              HDFC Bank
1                    Maruti Suzuki India
2                             ICICI Bank
3                     Larsen & Toubro Ltd
4                           Axis Bank Ltd
5                     State Bank of India
6                                NTPC Ltd
7                 Reliance industries Ltd
8                             Infosys Ltd
9                              Bosch Ltd.
10                 Hindustan Unilever Ltd
11                     Hero Motocorp Ltd.
12                       Linde India Ltd.
13                     Tech Mahindra Ltd.
14                      GAIL (India) Ltd.
15     Sun Pharmaceutical Industries Ltd.
16              Jindal Steel & Power Ltd.
17                  Ultratech Cement Ltd.
18                         Bank Of Baroda
19                               SRF Ltd.
20                     Bharti Airtel Ltd.
21                    Ambuja Cements Ltd.
22                    United Spirits Ltd.
23                  Exide Industries Ltd.
24  Kalpataru Projects International Ltd.
25                 KNR Constructions Ltd.
26                     Cummins India Ltd.
27                      Bharat Forge Ltd.
28                             Cipla Ltd.
29                         Blue Star Ltd.
30                         ABB India Ltd.
31        SBI Life Insurance Company Ltd.
32                            Voltas Ltd.
33                           Thermax Ltd.
34            Gujarat State Petronet Ltd.
35             Data Patterns (India) Ltd.
36                    Sun TV Network Ltd.
37                Zydus Lifesciences Ltd.
38            Solar Industries India Ltd.
39             AU Small Finance Bank Ltd.
40                     Ashok Leyland Ltd.
41                            Crisil Ltd.
42             Carborundum Universal Ltd.
43           Kaynes Technology India Ltd.
44              JK Tyre & Industries Ltd.
45             Balkrishna Industries Ltd.
46          Coromandel International Ltd.
47                         SKF India Ltd.
48               Hindalco Industries Ltd.
49                  Sundaram Finance Ltd.
50                               ITC Ltd.
51                   Ashoka Buildcon Ltd.
52                 Blue Dart Express Ltd.
53          Garware Technical Fibres Ltd.
54                  Tata Technologies Ltd
55    Indian Renewable Energy Development
56                   Hawkins Cookers Ltd.
57   Power Grid Corporation Of India Ltd.

                                       equity_name  equity_code  Asset
0                                    HDFC Bank Ltd       500180  5.34%
1                         MARUTI SUZUKI INDIA LTD.       532500  4.78%
2                                  ICICI BANK LTD.       532174  4.50%
3                             LARSEN & TOUBRO LTD.       500510  4.27%
4                                   AXIS BANK LTD.       532215  4.01%
5                              STATE BANK OF INDIA       500112  3.60%
6                                        NTPC LTD.       532555  3.57%
7                         RELIANCE INDUSTRIES LTD.       500325  2.97%
8                                     INFOSYS LTD.       500209  2.77%
9                                       BOSCH LTD.       500530  2.55%
10                         HINDUSTAN UNILEVER LTD.       500696  2.46%
11                              HERO MOTOCORP LTD.       500182  2.41%
12                             Linde India Limited       523457  2.33%
13                              TECH MAHINDRA LTD.       532755  2.22%
14                               GAIL (INDIA) LTD.       532155  2.16%
15              SUN PHARMACEUTICAL INDUSTRIES LTD.       524715  2.14%
16                       JINDAL STEEL & POWER LTD.       532286  2.13%
17                           ULTRATECH CEMENT LTD.       532538  1.91%
18                                  BANK OF BARODA       532134  1.81%
19                                        SRF LTD.       503806  1.74%
20                              BHARTI AIRTEL LTD.       532454  1.74%
21                             AMBUJA CEMENTS LTD.       500425  1.69%
22                             UNITED SPIRITS LTD.       532432  1.65%
23                           EXIDE INDUSTRIES LTD.       500086  1.47%
24            Kalpataru Projects International Ltd       522287  1.45%
25                          KNR CONSTRUCTIONS LTD.       532942  1.44%
26                              CUMMINS INDIA LTD.       500480  1.31%
27                               BHARAT FORGE LTD.       500493  1.29%
28                                      CIPLA LTD.       500087  1.27%
29                                  BLUE STAR LTD.       500067  1.25%
30                                ABC INDIA LTD.-$       520123  1.22%
31                  SBI Life Insurance Company Ltd       540719  1.17%
32                                     VOLTAS LTD.       500575  1.14%
33                                    THERMAX LTD.       500411  1.06%
34                     GUJARAT STATE PETRONET LTD.       532702  1.04%
35                       Data Patterns (India) Ltd       543428  1.03%
36                             SUN TV NETWORK LTD.       532733  1.03%
37                          Zydus Lifesciences Ltd       532321  1.02%
38                     SOLAR INDUSTRIES INDIA LTD.       532725  1.01%
39                       AU Small Finance Bank Ltd       540611  1.00%
40                              ASHOK LEYLAND LTD.       500477  0.99%
41                                     CRISIL LTD.       500092  0.98%
42                      CARBORUNDUM UNIVERSAL LTD.       513375  0.97%
43                     Kaynes Technology India Ltd       543664  0.96%
44                       JK TYRE & INDUSTRIES LTD.       530007  0.91%
45                    BALKRISHNA INDUSTRIES LTD.-$       502355  0.90%
46                   COROMANDEL INTERNATIONAL LTD.       506395  0.88%
47                                   SKF India Ltd       500472  0.73%
48                        HINDALCO INDUSTRIES LTD.       500440  0.72%
49                           SUNDARAM FINANCE LTD.       590071  0.71%
50                                        ITC LTD.       500875  0.64%
51                            ASHOKA BUILDCON LTD.       533271  0.57%
52                          BLUE DART EXPRESS LTD.       526612  0.54%
53                    Garware Technical Fibres Ltd       509557  0.52%
54                           Tata Technologies Ltd       544028  0.35%
55  Indian Renewable Energy Development Agency Ltd       544026  0.31%
56                          HAWKINS COOKERS LTD.-$       508486  0.30%
57            POWER GRID CORPORATION OF INDIA LTD.       532898  0.27%
                                     Name  \
0                              HDFC Bank
1                    Maruti Suzuki India
2                             ICICI Bank
3                     Larsen & Toubro Ltd
4                           Axis Bank Ltd
5                     State Bank of India
6                                NTPC Ltd
7                 Reliance industries Ltd
8                             Infosys Ltd
9                              Bosch Ltd.
10                 Hindustan Unilever Ltd
11                     Hero Motocorp Ltd.
12                       Linde India Ltd.
13                     Tech Mahindra Ltd.
14                      GAIL (India) Ltd.
15     Sun Pharmaceutical Industries Ltd.
16              Jindal Steel & Power Ltd.
17                  Ultratech Cement Ltd.
18                         Bank Of Baroda
19                               SRF Ltd.
20                     Bharti Airtel Ltd.
21                    Ambuja Cements Ltd.
22                    United Spirits Ltd.
23                  Exide Industries Ltd.
24  Kalpataru Projects International Ltd.
25                 KNR Constructions Ltd.
26                     Cummins India Ltd.
27                      Bharat Forge Ltd.
28                             Cipla Ltd.
29                         Blue Star Ltd.
30                         ABB India Ltd.
31        SBI Life Insurance Company Ltd.
32                            Voltas Ltd.
33                           Thermax Ltd.
34            Gujarat State Petronet Ltd.
35             Data Patterns (India) Ltd.
36                    Sun TV Network Ltd.
37                Zydus Lifesciences Ltd.
38            Solar Industries India Ltd.
39             AU Small Finance Bank Ltd.
40                     Ashok Leyland Ltd.
41                            Crisil Ltd.
42             Carborundum Universal Ltd.
43           Kaynes Technology India Ltd.
44              JK Tyre & Industries Ltd.
45             Balkrishna Industries Ltd.
46          Coromandel International Ltd.
47                         SKF India Ltd.
48               Hindalco Industries Ltd.
49                  Sundaram Finance Ltd.
50                               ITC Ltd.
51                   Ashoka Buildcon Ltd.
52                 Blue Dart Express Ltd.
53          Garware Technical Fibres Ltd.
54                  Tata Technologies Ltd
55    Indian Renewable Energy Development
56                   Hawkins Cookers Ltd.
57   Power Grid Corporation Of India Ltd.

                                       equity_name  equity_code  Asset
0                                    HDFC Bank Ltd       500180  5.34%
1                         MARUTI SUZUKI INDIA LTD.       532500  4.78%
2                                  ICICI BANK LTD.       532174  4.50%
3                             LARSEN & TOUBRO LTD.       500510  4.27%
4                                   AXIS BANK LTD.       532215  4.01%
5                              STATE BANK OF INDIA       500112  3.60%
6                                        NTPC LTD.       532555  3.57%
7                         RELIANCE INDUSTRIES LTD.       500325  2.97%
8                                     INFOSYS LTD.       500209  2.77%
9                                       BOSCH LTD.       500530  2.55%
10                         HINDUSTAN UNILEVER LTD.       500696  2.46%
11                              HERO MOTOCORP LTD.       500182  2.41%
12                             Linde India Limited       523457  2.33%
13                              TECH MAHINDRA LTD.       532755  2.22%
14                               GAIL (INDIA) LTD.       532155  2.16%
15              SUN PHARMACEUTICAL INDUSTRIES LTD.       524715  2.14%
16                       JINDAL STEEL & POWER LTD.       532286  2.13%
17                           ULTRATECH CEMENT LTD.       532538  1.91%
18                                  BANK OF BARODA       532134  1.81%
19                                        SRF LTD.       503806  1.74%
20                              BHARTI AIRTEL LTD.       532454  1.74%
21                             AMBUJA CEMENTS LTD.       500425  1.69%
22                             UNITED SPIRITS LTD.       532432  1.65%
23                           EXIDE INDUSTRIES LTD.       500086  1.47%
24            Kalpataru Projects International Ltd       522287  1.45%
25                          KNR CONSTRUCTIONS LTD.       532942  1.44%
26                              CUMMINS INDIA LTD.       500480  1.31%
27                               BHARAT FORGE LTD.       500493  1.29%
28                                      CIPLA LTD.       500087  1.27%
29                                  BLUE STAR LTD.       500067  1.25%
30                                ABC INDIA LTD.-$       520123  1.22%
31                  SBI Life Insurance Company Ltd       540719  1.17%
32                                     VOLTAS LTD.       500575  1.14%
33                                    THERMAX LTD.       500411  1.06%
34                     GUJARAT STATE PETRONET LTD.       532702  1.04%
35                       Data Patterns (India) Ltd       543428  1.03%
36                             SUN TV NETWORK LTD.       532733  1.03%
37                          Zydus Lifesciences Ltd       532321  1.02%
38                     SOLAR INDUSTRIES INDIA LTD.       532725  1.01%
39                       AU Small Finance Bank Ltd       540611  1.00%
40                              ASHOK LEYLAND LTD.       500477  0.99%
41                                     CRISIL LTD.       500092  0.98%
42                      CARBORUNDUM UNIVERSAL LTD.       513375  0.97%
43                     Kaynes Technology India Ltd       543664  0.96%
44                       JK TYRE & INDUSTRIES LTD.       530007  0.91%
45                    BALKRISHNA INDUSTRIES LTD.-$       502355  0.90%
46                   COROMANDEL INTERNATIONAL LTD.       506395  0.88%
47                                   SKF India Ltd       500472  0.73%
48                        HINDALCO INDUSTRIES LTD.       500440  0.72%
49                           SUNDARAM FINANCE LTD.       590071  0.71%
50                                        ITC LTD.       500875  0.64%
51                            ASHOKA BUILDCON LTD.       533271  0.57%
52                          BLUE DART EXPRESS LTD.       526612  0.54%
53                    Garware Technical Fibres Ltd       509557  0.52%
54                           Tata Technologies Ltd       544028  0.35%
55  Indian Renewable Energy Development Agency Ltd       544026  0.31%
56                          HAWKINS COOKERS LTD.-$       508486  0.30%
57            POWER GRID CORPORATION OF INDIA LTD.       532898  0.27%

In [28]:
# import time

# max_retries = 50
# b = BSE()
# def bsc(code,asset):
#     # Replace this with the code that might raise an error
#     # result = 1 / 0  # Example causing a ZeroDivisionError

#     quote = b.getQuote(str(code))
#     data = []
#     data.append(quote["companyName"])
#     data.append(quote["previousClose"])
#     data.append(quote["currentValue"])
#     data.append(quote["updatedOn"])
#     data.append(float(asset[:-1]))
#     previous_closing_price = 100
#     current_closing_price = 110
#     portfolio_percentage = 2.5
#     total_portfolio_value = 66000
#     stock_value = (float(asset[:-1]) / 100) * total_portfolio_value

#     # Calculate change in stock value
#     change_in_stock_value = (quote["currentValue"] - quote['previousClose']) * (stock_value / quote['previousClose'])

#     # Calculate new portfolio value
#     new_portfolio_value = total_portfolio_value + change_in_stock_value

#     # Calculate percent change
#     percent_change = (change_in_stock_value / total_portfolio_value) * 100
#     data.append(percent_change)
#     return data

# quote = [["CompanyName","previousClose","currentValue","updatedOn","Asset","percent_change"]]
# codelist = result_dataframe['equity_code']
# assetlist = result_dataframe['Asset']
# attempt =0
# for code,asset in zip(codelist,assetlist):
#     try:
#                 bsc1 = bsc(code,asset)
#                 quote.append(bsc1)
#             # except SpecificException as specific_exception:
#             #     print(f"Error in bsc function for code {code}: {specific_exception}")
#             #     print("Retrying...")
#             #     time.sleep(1)  # You can add a delay between retries if needed
#             #     # Continue to the next iteration of the loop to retry with the same value
#             #     continue
#     except Exception as e:
#                 print(f"Attempt {attempt} failed with error: {e}")
#                 if attempt < max_retries:
#                     print("Retrying...")
#                     attempt+=1
#                     time.sleep(1)  # You can add a delay between retries if needed
#                 else:
#                     print(f"Max attempts reached. Exiting...")
#                     # You may choose to handle the error or raise it again
#                     raise




# # Retry loop
# # for attempt in range(1, max_retries + 1):
# #     try:
# #       codelist = result_dataframe['equity_code']
# #       for code in codelist:
# #         bsc1 = bsc(code)
# #         quote.append(bsc)
# #         # If there's no error, break out of the loop
# #       # break
# #     except Exception as e:
# #         print(f"Attempt {attempt} failed with error: {e}")
# #         if attempt < max_retries:
# #             print("Retrying...")
# #             time.sleep(1)  # You can add a delay between retries if needed
# #         else:
# #             print(f"Max attempts reached. Exiting...")
# #             # You may choose to handle the error or raise it again
# #             raise

In [29]:
import time
# from BSE_module import BSE  # Assuming BSE_module is the module containing the BSE class

max_retries = 50
b = BSE()

def bsc(code, asset):
    try:
        quote = b.getQuote(str(code))
        data = []
        data.append(quote["companyName"])
        data.append(float(quote["previousClose"]))
        data.append(float(quote["currentValue"]))
        data.append(quote["updatedOn"])
        data.append(float(asset[:-1]))
        total_portfolio_value = 114.77
        stock_value = (float(asset[:-1]) / 100) * total_portfolio_value

        # Calculate change in stock value
        change_in_stock_value = (data[2] - data[1]) * (stock_value / data[1])

        # Calculate new portfolio value
        new_portfolio_value = total_portfolio_value + change_in_stock_value

        # Calculate percent change
        percent_change = (change_in_stock_value / total_portfolio_value) * 100
        data.append(percent_change)
        return data
    except Exception as e:
        print(f"Error processing code {code}: {e}")
        return None

quote = [["CompanyName","previousClose","currentValue","updatedOn","Asset","percent_change"]]
codelist = result_dataframe['equity_code']
assetlist = result_dataframe['Asset']
attempt = 0

for code, asset in zip(codelist, assetlist):
    while attempt < max_retries:
        try:
            bsc1 = bsc(code, asset)
            if bsc1 is not None:
                quote.append(bsc1)
                break  # Break the retry loop if successful
            else:
                print("Retrying...")
                attempt += 1
                time.sleep(1)  # Adding a delay between retries
        except Exception as e:
            print(f"Attempt {attempt + 1} failed with error: {e}")
            if attempt < max_retries - 1:
                print("Retrying...")
                attempt += 1
                time.sleep(1)  # Adding a delay between retries
            else:
                print("Max attempts reached. Exiting...")
                raise

Error processing code 500182: 'companyName'
Retrying...
Error processing code 500067: 'companyName'
Retrying...
Error processing code 500067: 'companyName'
Retrying...
Error processing code 532702: 'companyName'
Retrying...
Error processing code 532725: 'companyName'
Retrying...
Error processing code 500875: 'companyName'
Retrying...

In [31]:
import csv
csv_file_path = 'output.csv'

# Writing to CSV
with open(csv_file_path, 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)

    # Write data
    csv_writer.writerows(quote)

# Stock_list['Asset'].to_csv('output.csv', index=False)